[package]
name = "keycloak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
actix-web-middleware-keycloak-auth = "0.4.0"
env_logger = "0.10.0"
log = "0.4.19"
serde = "1.0.175"
