version: "3.1"
services:
  # web:
  #   build: .
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=password
  #     - spring.mail.host=mailhog
  #     - spring.mail.port=1025
  #     # - spring.mail.username=${MAIL_USER}
  #     # - spring.mail.password=${MAIL_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    #build: infrastructure/keycloak
    command: "start-dev --import-realm"
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    # env_file:
    #   - .env
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=loempia
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    volumes:
      - ./data/keycloak/:/opt/keycloak/data/import/

      # https://stackoverflow.com/questions/73519347/how-can-i-define-multiple-schemas-on-a-postgresql-docker-compose-instance
  database:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./../spool/db:/var/lib/postgresql/data
      - ./data/initdb:/docker-entrypoint-initdb.d

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
